In [26]:
import re
import pandas as pd
import pickle
from tqdm import tqdm
import dill

from konlpy.tag import Twitter

In [27]:
twitter = Twitter()

In [4]:
books_all = pd.read_csv('D:/taeking/bigdata/books_all.csv')

In [5]:
books_all.sample(3)

Unnamed: 0                   name     author  \
63            63                  고구려 4        김진명   
1133         237                크로우 걸 2  에리크 악슬 순드   
276          276  그 산이 정말 거기 있었을까 (양장본)        박완서   

                                                   text  \
63     출판사 리뷰 김진명의 고구려 는 고구려 역사 중 가장 극적인 시대로 손꼽히는 미천...   
1133   출판사 리뷰 스톡홀름에서 벌어지는 끔찍한 소년 살해 사건 그리고 부모에 의해 숨죽...   
276    이 책은 박완서의 의 후속편으로 만 부 돌파 기념 출간 년만에 양장본으로 새롭게 ...   

                                                  image  
63    http://image.bandinlunis.com/upload/product/33...  
1133  http://image.bandinlunis.com/upload/product/39...  
276   http://image.bandinlunis.com/upload/product/38...

In [6]:
books_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 5 columns):
Unnamed: 0    1196 non-null int64
name          1196 non-null object
author        1196 non-null object
text          1166 non-null object
image         1196 non-null object
dtypes: int64(1), object(4)
memory usage: 46.8+ KB


In [7]:
book_sample = books_all.sample(1)

In [23]:
book_sample

Unnamed: 0  name   author  \
523         223  잡동사니  에쿠니 가오리   

                                                  text  \
523   출판사 리뷰 두 세기를 뒤흔든 희대의 감성 에쿠니 가오리가 그리는 위험한 스캔들 ...   

                                                 image  
523  http://image.bandinlunis.com/upload/product/35...

In [30]:
txt = book_sample['text'][523]
txt

' 출판사 리뷰 두 세기를 뒤흔든 희대의 감성 에쿠니 가오리가 그리는 위험한 스캔들 두 세기를 뒤흔든 희대의 감성 에쿠니 가오리의 최신 장편소설 잡동사니 는 대 소녀와 대 여성의 상반된 감성을 동시에 그려낸 본격 연애소설이다 열다섯 살 소녀와 마흔다섯 살 여인의 이야기가 옴니버스식으로 진행되는 이 소설은 죽음과 삶을 넘나드는 철학적 이야기도 사랑에 목숨을 건 절박한 러브스토리도 아니다 다만 에쿠니 가오리의 소설이 늘 그렇듯 그녀의 주인공들은 스캔들이라고 해도 좋을 정도의 위험한 관계 속에서 격정적인 사랑을 한다 해바라기처럼 남편만을 바라보며 사는 마흔다섯 살 슈코는 때때로 어머니와 단 둘이 여행을 떠난다 남편에게서 벗어나기 위해 아니 어쩌면 그에게서 벗어나지 않았다는 것을 확인하기 위해 어머니와 함께 떠난 휴양지에서 슈코는 바비 인형을 닮은 소녀를 만나게 되고 어린아이도 여자도 아닌 그 소녀만이 내뿜는 매력에 그녀는 시선을 빼앗기고 만다 그리고 이 만남을 계기로 슈코와 소녀 그리고 슈코 남편과의 미묘한 관계가 시작된다 이 이야기는 낯선 남자와의 정사 남편의 여자 친구 미성년자와의 관계 등 사랑과 집착 그리고 도덕성의 아슬아슬한 경계를 오간다 혹자는 이 이야기를 두고 비정상적인 관계라 칭하기도 한다 하지만 저자는 내리쬐는 햇살 알싸하게 응축된 공기 여기저기 널려 있는 물건 등 겉으로 드러나지는 않지만 절제된 표현을 통해 모든 감정을 섬세하게 응축시킴으로써 이 모든 관계를 도덕적 잣대에서 해방시킨다 위험한 관계 그 안에서 흐르는 미묘한 감정 이 모든 것을 세련된 감성으로 통제한 에쿠니 가오리식 완벽한 연애소설을 이제 만나보자 사랑의 환희와 두려움 그 뒤에 숨겨진 수많은 감정의 실타래를 섬세하게 풀어낸 소설 이 이야기는 푸껫 해변에서 시작된다 사랑하는 남편 곁을 떠나 잠시 푸껫으로 여행 온 슈코는 그곳에서 바비 인형을 닮은 소녀를 만나고 그 아이에게 시선을 빼앗긴다 그리고 그 만남을 시작으로 두 여인의 이야기가 번갈아가며 진행된다 에쿠니 가오리는 처음 이 소설을 쓸

In [32]:
book_nouns =  twitter.nouns(txt)
book_nouns

['출판사',
 '리뷰',
 '두',
 '세기',
 '뒤',
 '대의',
 '감성',
 '쿠니',
 '가오리',
 '스캔들',
 '두',
 '세기',
 '뒤',
 '대의',
 '감성',
 '쿠니',
 '가오리',
 '최신',
 '장편소설',
 '잡',
 '동사',
 '소녀',
 '여성',
 '상반',
 '감성',
 '동시',
 '본격',
 '연애소설',
 '열',
 '다섯',
 '살',
 '소녀',
 '마흔',
 '다섯',
 '살',
 '여인',
 '이야기',
 '옴니버스',
 '이',
 '소설',
 '죽음',
 '삶',
 '철학',
 '이야기',
 '사랑',
 '목숨',
 '건',
 '절박',
 '러브스토리',
 '다만',
 '쿠니',
 '가오리',
 '소설',
 '늘',
 '그녀',
 '주인공',
 '스캔들',
 '해도',
 '정도',
 '관계',
 '속',
 '격정',
 '사랑',
 '해바라기',
 '남편',
 '마흔',
 '다섯',
 '살',
 '슈코',
 '어머니',
 '단',
 '둘',
 '여행',
 '남편',
 '위해',
 '어쩌면',
 '그',
 '것',
 '위해',
 '어머니',
 '휴양지',
 '슈코',
 '바비',
 '인형',
 '소녀',
 '여자도',
 '그',
 '소녀',
 '내뿜',
 '매력',
 '그녀',
 '시선',
 '만',
 '이',
 '만남',
 '계기',
 '슈코',
 '소녀',
 '슈코',
 '남편',
 '미묘',
 '관계',
 '이',
 '이야기',
 '낯선',
 '남자',
 '정사',
 '남편',
 '여자',
 '친구',
 '미성년',
 '관계',
 '등',
 '사랑',
 '집착',
 '도덕성',
 '아슬아슬',
 '경계',
 '혹',
 '이',
 '이야기',
 '비정상',
 '관계',
 '칭하기',
 '저자',
 '내리쬐',
 '햇살',
 '알',
 '응축',
 '공기',
 '여기저기',
 '널려',
 '물건',
 '등',
 '겉',
 '절제',
 '표현',
 '통해',
 '모든',
 '감정',
 '섬세',
 '응축'

In [33]:
from gensim.models.word2vec import Word2Vec
from multiprocessing import cpu_count

D:\Anaconda3\lib\site-packages\gensim\utils.py:1209: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [47]:
test2_img = pd.read_excel('D:/taeking/bigdata/test2_img_drop2.xlsx')

In [48]:
len(test2_img)

12497

In [49]:
test2_img.sample(3)

연월                                            전시제목  \
8039   201210            이인성 판화 & 아트 상품展 :: Original Printing   
12227  201312                   SEOULdabada :: Conceptual Art   
2386   201011  Invitation to the Bodyscape - 김지희展 :: Painting   

                                                      링크  \
8039   http://www.arthub.co.kr/sub01/board03_view.htm...   
12227  http://www.arthub.co.kr/sub01/board03_view.htm...   
2386   http://www.arthub.co.kr/sub01/board03_view.htm...   

                                                    전시작가  \
8039                             ['이인성(Lee Insung 李仁星)']   
12227  ['LAURA TRUJILLO', 'YOSHIHISA NAKAO', 'YUJONG ...   
2386                                  ['김지희(Kim Jihee)']   

                          전시일정                초대일시  \
8039   2012-10-22 ▶ 2012-11-10                  없음   
12227  2013-12-20 ▶ 2014-01-21  2013-12-20 PM 6:00   
2386   2010-11-24 ▶ 2010-11-30  2010-11-24 PM 6:00   

                                   관람시간                              전시장소  \
8039           Open 10:00 ~ Close 19:00                     갤러리G  다른전시 보기   
12227  Open 11:00 ~ Close 19:00(월요일 휴관)  갤러리 시:작(Gallery Si:Jac)  다른전시 보기   
2386           Open 10:30 ~ Close 18:30      노암갤러리(NOAM GALLERY)  다른전시 보기   

                     주소           연락처                           홈페이지   아티클  \
8039   대구시 중구 봉산문화길 42   053-421-3559                            NaN  ['']   
12227  서울시 종로구 인사동 39     02-735-6266  www.artandsmart-gallery.co.kr  ['']   
2386   서울시 종로구 인사동 133    02-720-2235                            NaN  ['']   

                                                     텍스트  \
8039   ● 이인성 판화 & 아트 상품展\n        근대 한국화단을 대표하는 화가 이인...   
12227  지난 3년간 ‘dabada’라는 \n        전시명으로 일본을 비롯하여 유럽 ...   
2386   ● Invitation to the Bodyscape: 김지희의 회화적 공간\n  ...   

                                                     이미지  
8039   http://arthub.co.kr/admin/admin_board_01/data/...  
12227  http://arthub.co.kr/admin/admin_board_01/data/...  
2386   http://arthub.co.kr/admin/admin_board_01/data/...

In [50]:
for i in tqdm(range(len(test2_img['텍스트']))):
    try: 
        if np.isnan(test2_img['텍스트'][i]):
            temp = ""
    except:
        temp = re.sub(r"[^가-힣ㄱ-ㅎㅏ-ㅣ0-9.,?!\s]", "", test2_img['텍스트'][i])
        temp = re.sub(r"[\n]", " ", temp)
        temp = re.sub(r"[\s]+", " ", temp)
    test2_img['텍스트'][i] = temp

  0%|                                                                                        | 0/12497 [00:00<?, ?it/s]D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
100%|████████████████████████████████████████████████████████████████████████████| 12497/12497 [07:00<00:00, 29.73it/s]


In [56]:
len(test2_img)

12497

In [53]:
test2_img['텍스트'].sample(3)

9419     봄, 여름, 가을, 겨울...우리의 사랑은 마치 반복되는 사계절과도 같다. 봄의 ...
3684     이효진 바탕의 색이 선명하게 올라올 때 쯤, 어떤 이야기를 만들어간다. 잔잔하게 ...
2801     솟아나는... 인체 속에 꽃 된 자연 나는 사람과 관계하는 모든 것이 어떤 점에서...
Name: 텍스트, dtype: object

In [57]:
test2_img_tw = []

for i in tqdm(range(len(test2_img['텍스트']))):
    try: 
        test2_img_tw.append(twitter.morphs(test2_img['텍스트'][i]))
    except:
        pass
    
len(test2_img_tw)

100%|████████████████████████████████████████████████████████████████████████████| 12497/12497 [06:08<00:00, 33.87it/s]


12497

In [58]:
with open('D:/taeking/bigdata/test2_img_drop2_tw.dill', 'wb') as fp:
    dill.dump(test2_img_tw, fp)

학습은 morphs,
문서당 벡터합은  noun, adj만 추려서,
비교는 cos-simul로 문서간 벡터합끼리

In [62]:
#하이퍼파라미터 세팅

num_features = 100
min_word_count = 10
num_workers = cpu_count()
context_size = 10
downsampling = 1e-3
seed=180816

In [63]:
#모델 생성#모델 생성
art2vec =Word2Vec( 
    sg=1, #skip-gram
    workers=cpu_count(),
    size=num_features,
    min_count=min_word_count,
    window=context_size,
    sample = downsampling,
)

In [64]:
art2vec.build_vocab(test2_img_tw)

In [65]:
art2vec.corpus_count

12497

In [66]:
art2vec.epochs

5

In [67]:
art2vec.train(test2_img_tw,total_examples=art2vec.corpus_count,epochs=art2vec.epochs) #학습 with tokens

(31307155, 43047365)

In [68]:
art2vec.save('D:/taeking/bigdata/word2vec_test2_img_tw.w2v')

In [69]:
art2vec.wv.most_similar('유화')

D:\Anaconda3\lib\site-packages\gensim\matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('아크릴', 0.7912366390228271),
 ('과슈', 0.7850642204284668),
 ('수채화', 0.7710666656494141),
 ('수채', 0.7429032325744629),
 ('콘테', 0.7387513518333435),
 ('판화', 0.7311594486236572),
 ('물감', 0.723939061164856),
 ('릭', 0.7172956466674805),
 ('목판', 0.7125094532966614),
 ('먹과', 0.6955099105834961)]

test2에 있는 전시마다 명사,형용사 뽑아내기

추후에 전시마다 벡터합을 구하는데 쓸 것임

In [72]:
test2_img_noun_adj = []

for i in  tqdm(range(len(test2_img))):
    pos = twitter.pos(test2_img['텍스트'][i])
    words = []
    
    for word, tag in pos:
        if tag == 'Adjective' or tag == 'Noun':
            words.append(word)
    test2_img_noun_adj.append(words)
    
len(test2_img_noun_adj)

100%|████████████████████████████████████████████████████████████████████████████| 12497/12497 [06:06<00:00, 34.12it/s]


12497

In [74]:
with open('D:/taeking/bigdata/test2_img_drop_noun_adj.dill', 'wb') as fp:
    dill.dump(test2_img_noun_adj, fp)

In [75]:
import numpy as np

In [117]:
# word_vector = np.zeros(100, dtype='float32')

In [118]:
# word_vector1 = art2vec.wv.get_vector('유화')
# word_vector1

In [119]:
# word_vector +=  word_vector1
# word_vector

In [123]:
1 / 2

0.5

In [120]:
# word_vector +=  word_vector1
# word_vector

In [151]:
test2_word_vector = []

for i in tqdm(range(len(test2_img_noun_adj))):
    
    del word_vector
    word_vector = np.zeros(100, dtype='float32')
    
    for word in test2_img_noun_adj[i]:
        lenth = len(test2_img_noun_adj[i])
        try:
            word_vector += art2vec.wv.get_vector(word)
        except:
            lenth -= 1
            
    if lenth != 0:
        word_vector = word_vector / len(test2_img_noun_adj[i])
    else:
        word_vector = np.zeros(100, dtype='float32')

    test2_word_vector.append((i, word_vector))
    
###
len(test2_word_vector)

  2%|█▋                                                                           | 284/12497 [00:00<00:17, 704.85it/s]D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()
100%|███████████████████████████████████████████████████████████████████████████| 12497/12497 [00:12<00:00, 997.01it/s]


12497

In [152]:
with open('D:/taeking/bigdata/test2_img_drop_word_vector.dill', 'wb') as fp:
    dill.dump(test2_word_vector, fp)

In [161]:
test2_word_vector[2]

(2, array([-0.10849402,  0.03875434, -0.00782112, -0.15287189,  0.21544802,
         0.09291635,  0.11214951, -0.18647079, -0.05315446, -0.14277941,
        -0.16848011,  0.00243843,  0.0642871 , -0.08617266, -0.0511617 ,
         0.03734321,  0.20652108,  0.21944287, -0.01641606,  0.13984281,
         0.02523988,  0.09961713,  0.03373871,  0.07551078,  0.11400174,
        -0.2003037 , -0.00866445, -0.00227314, -0.04060761,  0.1728599 ,
        -0.03681484, -0.10722148,  0.03556489, -0.0323275 ,  0.12471646,
        -0.06450006,  0.29404262, -0.0142717 , -0.08171368,  0.006253  ,
         0.02701707, -0.19804327,  0.02948565, -0.14774822,  0.14070216,
        -0.0988647 ,  0.04107279,  0.14358747, -0.10987714, -0.02674144,
        -0.03847885, -0.14095266, -0.3401821 ,  0.17559206,  0.02122494,
        -0.00137528,  0.01795895,  0.2671238 ,  0.15630656, -0.02777207,
        -0.10298566, -0.30192596, -0.01730721,  0.17894146, -0.20970105,
        -0.04805131, -0.10189279,  0.11307803,  

test2_img의 전시들을 다 벡터화 했으니 샘플 벡터 만들고 비교해보자

Test1

In [128]:
i = 0 #test index
###
word_vector1 = np.zeros(100, dtype='float32')
    
for word in test2_img_noun_adj[i]:
    lenth = len(test2_img_noun_adj[i])
    try:
        word_vector1 += art2vec.wv.get_vector(word)
    except:
        lenth -= 1
            
if lenth != 0:
    word_vector1 = word_vector1 / len(test2_img_noun_adj[i])
else:
    word_vector1 = np.zeros(100, dtype='float32')

print(test2_img['전시작가'][i])
print(test2_img['링크'][i])
word_vector1

['이다(Ree Da)']
http://www.arthub.co.kr/sub01/board03_view.htm?No=394


array([-1.02392882e-01,  2.29677409e-02, -3.82115729e-02, -2.01064363e-01,
        1.50631130e-01,  7.85825774e-02,  1.35532826e-01, -1.80165589e-01,
       -5.31163812e-02, -7.17369542e-02, -1.10093541e-01, -2.38660853e-02,
        1.23125790e-02, -8.38315934e-02, -3.86759527e-02,  2.42004711e-02,
        2.56770372e-01,  1.86602145e-01, -4.00883220e-02,  1.65396094e-01,
        3.16839032e-02,  1.00434415e-01,  3.23467664e-02,  2.26214882e-02,
        6.35605231e-02, -2.15275079e-01, -7.99703237e-04,  8.67736153e-03,
       -3.30004059e-02,  1.46602258e-01, -4.19907980e-02, -8.20691884e-02,
       -1.35558322e-02,  5.54897040e-02,  1.43635795e-01, -2.88893450e-02,
        2.75921911e-01,  1.31248729e-02, -9.93128419e-02, -4.46337610e-02,
        3.49192806e-02, -1.99046820e-01, -4.22898447e-03, -1.45450816e-01,
        1.30587921e-01, -1.20037995e-01,  5.43734580e-02,  1.47316068e-01,
       -1.55906960e-01, -6.73795342e-02,  1.16555328e-02, -1.52034178e-01,
       -2.79600292e-01,  

In [162]:
art2vec.wv.cosine_similarities(word_vector1, [test2_word_vector[i][1] for i in range(len(test2_word_vector[:5]))])

array([1.0000001 , 0.9201822 , 0.9619708 , 0.94752896, 0.91218454],
      dtype=float32)

In [166]:
result = art2vec.wv.cosine_similarities(word_vector1, [test2_word_vector[i][1] for i in range(len(test2_word_vector))])

In [168]:
type(result)

numpy.ndarray

In [171]:
result

array([1.0000001 , 0.9201822 , 0.9619708 , ..., 0.8659238 , 0.92813724,
       0.9408911 ], dtype=float32)

In [178]:
count = 0
for i in result:
    if np.isnan(i):
        count +=1
count        

24

In [183]:
result_sorted = np.sort(result)

In [182]:
result_index = np.argsort(result)

In [184]:
result_sorted = result_sorted[::-1]
result_sorted

array([       nan,        nan,        nan, ..., 0.601764  , 0.55443233,
       0.41658914], dtype=float32)

In [185]:
result_index = result_index[::-1]
result_index

array([  562,  5357, 11789, ...,  4848,  4524,  1885], dtype=int64)

In [188]:
len(result_sorted)

12497

In [187]:
result_drop_nan = []

for i in range(len(result_sorted)):
    if np.isnan(result_sorted[i]):
        pass
    else: 
        result_drop_nan.append((result_index[i], result_sorted[i]))

len(result_drop_nan)

12473

In [204]:
result_drop_nan[:10]

[(0, 1.0000001),
 (469, 0.9775196),
 (4328, 0.9740839),
 (4528, 0.973471),
 (945, 0.9720874),
 (1580, 0.97070795),
 (3671, 0.9698598),
 (1343, 0.96965486),
 (394, 0.96956104),
 (8617, 0.9695401)]

In [205]:
result_drop_nan[:10][1][0]

469

In [221]:
test2_img['전시제목'][0]

'이다展 :: Painting'

In [223]:
print(test2_img['링크'][0])

http://www.arthub.co.kr/sub01/board03_view.htm?No=394


In [208]:
for i in range(len(result_drop_nan[:10])):
    print(result_drop_nan[:10][i][0])
    print(test2_img['링크'][result_drop_nan[:10][i][0]])

0
http://www.arthub.co.kr/sub01/board03_view.htm?No=394
469
http://www.arthub.co.kr/sub01/board03_view.htm?No=428
4328
http://www.arthub.co.kr/sub01/board03_view.htm?No=5045
4528
http://www.arthub.co.kr/sub01/board03_view.htm?No=5617
945
http://www.arthub.co.kr/sub01/board03_view.htm?No=1047
1580
http://www.arthub.co.kr/sub01/board03_view.htm?No=1777
3671
http://www.arthub.co.kr/sub01/board03_view.htm?No=4704
1343
http://www.arthub.co.kr/sub01/board03_view.htm?No=1390
394
http://www.arthub.co.kr/sub01/board03_view.htm?No=489
8617
http://www.arthub.co.kr/sub01/board03_view.htm?No=10087


In [225]:
test2_img_noun_adj[0]

['욕망',
 '재현',
 '중',
 '의적',
 '알리바이',
 '색',
 '색',
 '욕',
 '욕',
 '얼핏',
 '색',
 '깔끔한',
 '마감',
 '단장',
 '예쁜',
 '그림',
 '화단',
 '의사',
 '아이콘',
 '연작',
 '화단',
 '트렌드',
 '연장',
 '선',
 '어디',
 '튕겨',
 '부산물',
 '중',
 '하나로',
 '무리는',
 '없으',
 '무릇',
 '도로',
 '경제',
 '채색',
 '고집',
 '앙증',
 '간결',
 '구성',
 '약간',
 '번',
 '림',
 '동반',
 '럭셔리',
 '면',
 '재질감',
 '거기',
 '깔끔하게',
 '마감',
 '전체',
 '인상',
 '감안',
 '때',
 '그렇',
 '동시',
 '청년',
 '작가',
 '외형',
 '동형',
 '너머',
 '그',
 '년대',
 '초반',
 '줄곧',
 '제시',
 '주제',
 '작품',
 '개별',
 '로부터',
 '그럴듯한',
 '스토리',
 '유추',
 '개별',
 '작업',
 '누적',
 '하나',
 '연쇄',
 '선명한',
 '수렴',
 '점',
 '그것',
 '도발',
 '직전',
 '폭력',
 '사회',
 '합의',
 '영원히',
 '영원히',
 '닉',
 '역설',
 '갖은',
 '적',
 '색욕',
 '년',
 '모종',
 '사고',
 '바닥',
 '널',
 '인물',
 '머리',
 '가마',
 '캔버스',
 '말단',
 '화면',
 '적신',
 '이',
 '짧은',
 '해설',
 '우리',
 '혈흔낭자',
 '익숙한',
 '사고',
 '장면',
 '법',
 '실제',
 '작품',
 '보랏빛',
 '면',
 '그',
 '위로',
 '얹힌',
 '굵은',
 '연분',
 '홍색',
 '라인',
 '수십',
 '가닥',
 '장식',
 '페인',
 '팅',
 '점',
 '이',
 '끔찍한',
 '대형',
 '사고',
 '전후',
 '인과',
 '서사',
 '단조',
 '구성',
 '속',
 '표면',
 '증발',


In [226]:
test2_img_noun_adj[469]

['허언증',
 '대중',
 '매체',
 '통해',
 '끊임없',
 '재생산',
 '일련',
 '시각',
 '이미지',
 '우리',
 '무의식',
 '저장',
 '욕망',
 '기계',
 '재현',
 '과정',
 '추적',
 '작가',
 '전통',
 '의미',
 '로서',
 '화가',
 '이미지',
 '비평가',
 '중간',
 '입장',
 '서서',
 '유사',
 '인지심리학',
 '차원',
 '문제',
 '의식',
 '도출',
 '대중',
 '매체',
 '이미지',
 '어떻',
 '우리',
 '욕망',
 '투사',
 '우리',
 '우리',
 '그',
 '이미지',
 '어떻',
 '어떻',
 '그것',
 '다시',
 '모조',
 '작가',
 '미술사',
 '하나',
 '도상',
 '자리',
 '누드',
 '모델',
 '포즈',
 '성적',
 '이미지',
 '노출',
 '가능한',
 '성인',
 '라면',
 '누구',
 '알',
 '수',
 '있는',
 '포르노그래피',
 '매일',
 '뉴스',
 '반복',
 '일상',
 '불안',
 '대화',
 '역',
 '우리',
 '안심',
 '각종',
 '끔찍한',
 '사건',
 '사고',
 '아이',
 '노',
 '것임',
 '어른',
 '욕망',
 '투영',
 '다양한',
 '인형',
 '여성',
 '신체',
 '훤히',
 '수영복',
 '치마',
 '성적',
 '판타지',
 '권선',
 '징',
 '악의',
 '교훈',
 '메시지',
 '그럴',
 '포장',
 '만화',
 '등',
 '섹슈얼리티',
 '폭력',
 '두드러지',
 '대중',
 '매체',
 '각종',
 '이미지',
 '작품',
 '주소',
 '재',
 '시리즈',
 '작업',
 '롤리타',
 '콤플렉스',
 '연상',
 '소녀',
 '아이스크림',
 '있거',
 '테디',
 '인형',
 '토끼',
 '인형',
 '표정',
 '제거',
 '채',
 '있는',
 '그',
 '달리',
 '루벤스',
 '작품',
 '법',
 '풍만',
 '모습',
 '도발',


Test2

In [227]:
i = 1 #test index
###
word_vector1 = np.zeros(100, dtype='float32')
    
for word in test2_img_noun_adj[i]:
    lenth = len(test2_img_noun_adj[i])
    try:
        word_vector1 += art2vec.wv.get_vector(word)
    except:
        lenth -= 1
            
if lenth != 0:
    word_vector1 = word_vector1 / len(test2_img_noun_adj[i])
else:
    word_vector1 = np.zeros(100, dtype='float32')

print(test2_img['전시작가'][i])
print(test2_img['링크'][i])
word_vector1

['주명덕(Joo Myungduck)']
http://www.arthub.co.kr/sub01/board03_view.htm?No=613


array([-0.07078881, -0.03097207, -0.04981715, -0.32116044,  0.17857906,
       -0.00111155,  0.14150032, -0.22254024, -0.06149027, -0.12884574,
       -0.18708989,  0.07672618,  0.0202234 , -0.05264746,  0.00730124,
        0.04532674,  0.21022066,  0.20394412, -0.04583438,  0.16698594,
        0.04948815,  0.07934804, -0.00155595,  0.0825165 ,  0.11978738,
       -0.177965  ,  0.02229265,  0.01589184, -0.0141812 ,  0.16986364,
       -0.03081656, -0.1488885 , -0.03350239, -0.05680348,  0.16337635,
       -0.11182233,  0.28674996, -0.03668781, -0.04199582,  0.03667241,
        0.05883292, -0.29574603,  0.02452743, -0.0643676 ,  0.08234114,
       -0.19371212,  0.10487982,  0.12275046, -0.00164159, -0.01830993,
       -0.02694061, -0.16431515, -0.31246036,  0.21526363,  0.06682777,
        0.03850302,  0.04595383,  0.27470204,  0.20688803, -0.06020997,
       -0.11736787, -0.23991327, -0.01055228,  0.24845451, -0.21903245,
        0.00190715, -0.10482546,  0.10950869,  0.07066224, -0.09

In [228]:
result = art2vec.wv.cosine_similarities(word_vector1, [test2_word_vector[i][1] for i in range(len(test2_word_vector))])

In [229]:
result_sorted = np.sort(result)
result_index = np.argsort(result)
result_sorted = result_sorted[::-1]
result_index = result_index[::-1]

result_drop_nan = []

for i in range(len(result_sorted)):
    if np.isnan(result_sorted[i]):
        pass
    else: 
        result_drop_nan.append((result_index[i], result_sorted[i]))

for i in range(len(result_drop_nan[:10])):
    print(result_drop_nan[:10][i][0])
    print(test2_img['링크'][result_drop_nan[:10][i][0]])

1
http://www.arthub.co.kr/sub01/board03_view.htm?No=613
6842
http://www.arthub.co.kr/sub01/board03_view.htm?No=8432
358
http://www.arthub.co.kr/sub01/board03_view.htm?No=374
1084
http://www.arthub.co.kr/sub01/board03_view.htm?No=1223
3103
http://www.arthub.co.kr/sub01/board03_view.htm?No=3588
4495
http://www.arthub.co.kr/sub01/board03_view.htm?No=5201
3563
http://www.arthub.co.kr/sub01/board03_view.htm?No=3890
3398
http://www.arthub.co.kr/sub01/board03_view.htm?No=4395
12349
http://www.arthub.co.kr/sub01/board03_view.htm?No=15142
9672
http://www.arthub.co.kr/sub01/board03_view.htm?No=11893


Test3

In [230]:
i = 2 #test index
###
word_vector1 = np.zeros(100, dtype='float32')
    
for word in test2_img_noun_adj[i]:
    lenth = len(test2_img_noun_adj[i])
    try:
        word_vector1 += art2vec.wv.get_vector(word)
    except:
        lenth -= 1
            
if lenth != 0:
    word_vector1 = word_vector1 / len(test2_img_noun_adj[i])
else:
    word_vector1 = np.zeros(100, dtype='float32')

print(test2_img['전시작가'][i])
print(test2_img['링크'][i])
# word_vector1

result = art2vec.wv.cosine_similarities(word_vector1, [test2_word_vector[i][1] for i in range(len(test2_word_vector))])

result_sorted = np.sort(result)
result_index = np.argsort(result)
result_sorted = result_sorted[::-1]
result_index = result_index[::-1]

result_drop_nan = []

for i in range(len(result_sorted)):
    if np.isnan(result_sorted[i]):
        pass
    else: 
        result_drop_nan.append((result_index[i], result_sorted[i]))

for i in range(len(result_drop_nan[:10])):
    print(result_drop_nan[:10][i][0])
    print(test2_img['링크'][result_drop_nan[:10][i][0]])

['이봉열(Lee Bongyeol)']
http://www.arthub.co.kr/sub01/board03_view.htm?No=4680
2
http://www.arthub.co.kr/sub01/board03_view.htm?No=4680
101
http://www.arthub.co.kr/sub01/board03_view.htm?No=227
214
http://www.arthub.co.kr/sub01/board03_view.htm?No=4502
940
http://www.arthub.co.kr/sub01/board03_view.htm?No=1113
727
http://www.arthub.co.kr/sub01/board03_view.htm?No=914
1650
http://www.arthub.co.kr/sub01/board03_view.htm?No=1884
2097
http://www.arthub.co.kr/sub01/board03_view.htm?No=2206
814
http://www.arthub.co.kr/sub01/board03_view.htm?No=923
1060
http://www.arthub.co.kr/sub01/board03_view.htm?No=1218
781
http://www.arthub.co.kr/sub01/board03_view.htm?No=775


Test4

In [231]:
i = 3 #test index
###
word_vector1 = np.zeros(100, dtype='float32')
    
for word in test2_img_noun_adj[i]:
    lenth = len(test2_img_noun_adj[i])
    try:
        word_vector1 += art2vec.wv.get_vector(word)
    except:
        lenth -= 1
            
if lenth != 0:
    word_vector1 = word_vector1 / len(test2_img_noun_adj[i])
else:
    word_vector1 = np.zeros(100, dtype='float32')

print(test2_img['전시작가'][i])
print(test2_img['링크'][i])
# word_vector1

result = art2vec.wv.cosine_similarities(word_vector1, [test2_word_vector[i][1] for i in range(len(test2_word_vector))])

result_sorted = np.sort(result)
result_index = np.argsort(result)
result_sorted = result_sorted[::-1]
result_index = result_index[::-1]

result_drop_nan = []

for i in range(len(result_sorted)):
    if np.isnan(result_sorted[i]):
        pass
    else: 
        result_drop_nan.append((result_index[i], result_sorted[i]))

for i in range(len(result_drop_nan[:10])):
    print(result_drop_nan[:10][i][0])
    print(test2_img['링크'][result_drop_nan[:10][i][0]])

['주송열(Joo Songyeul)']
http://www.arthub.co.kr/sub01/board03_view.htm?No=4283
3
http://www.arthub.co.kr/sub01/board03_view.htm?No=4283
1718
http://www.arthub.co.kr/sub01/board03_view.htm?No=1891
5087
http://www.arthub.co.kr/sub01/board03_view.htm?No=6143
12143
http://www.arthub.co.kr/sub01/board03_view.htm?No=14557
7089
http://www.arthub.co.kr/sub01/board03_view.htm?No=8668
3818
http://www.arthub.co.kr/sub01/board03_view.htm?No=4826
5747
http://www.arthub.co.kr/sub01/board03_view.htm?No=7272
2772
http://www.arthub.co.kr/sub01/board03_view.htm?No=3504
7341
http://www.arthub.co.kr/sub01/board03_view.htm?No=9232
10668
http://www.arthub.co.kr/sub01/board03_view.htm?No=12792


Test5

In [232]:
i = 4 #test index
###
word_vector1 = np.zeros(100, dtype='float32')
    
for word in test2_img_noun_adj[i]:
    lenth = len(test2_img_noun_adj[i])
    try:
        word_vector1 += art2vec.wv.get_vector(word)
    except:
        lenth -= 1
            
if lenth != 0:
    word_vector1 = word_vector1 / len(test2_img_noun_adj[i])
else:
    word_vector1 = np.zeros(100, dtype='float32')

print(test2_img['전시작가'][i])
print(test2_img['링크'][i])
# word_vector1

result = art2vec.wv.cosine_similarities(word_vector1, [test2_word_vector[i][1] for i in range(len(test2_word_vector))])

result_sorted = np.sort(result)
result_index = np.argsort(result)
result_sorted = result_sorted[::-1]
result_index = result_index[::-1]

result_drop_nan = []

for i in range(len(result_sorted)):
    if np.isnan(result_sorted[i]):
        pass
    else: 
        result_drop_nan.append((result_index[i], result_sorted[i]))

for i in range(len(result_drop_nan[:10])):
    print(result_drop_nan[:10][i][0])
    print(test2_img['링크'][result_drop_nan[:10][i][0]])

['임동식(Rim Dongsik)']
http://www.arthub.co.kr/sub01/board03_view.htm?No=133
4
http://www.arthub.co.kr/sub01/board03_view.htm?No=133
9715
http://www.arthub.co.kr/sub01/board03_view.htm?No=11840
12285
http://www.arthub.co.kr/sub01/board03_view.htm?No=15063
5254
http://www.arthub.co.kr/sub01/board03_view.htm?No=6140
4367
http://www.arthub.co.kr/sub01/board03_view.htm?No=5689
8830
http://www.arthub.co.kr/sub01/board03_view.htm?No=10555
2125
http://www.arthub.co.kr/sub01/board03_view.htm?No=2363
2294
http://www.arthub.co.kr/sub01/board03_view.htm?No=2580
9458
http://www.arthub.co.kr/sub01/board03_view.htm?No=11671
7974
http://www.arthub.co.kr/sub01/board03_view.htm?No=9808
